In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('ds.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
y=data['Profit']

In [7]:
type(y)

pandas.core.series.Series

In [8]:
y=y.values

In [9]:
type(y)

numpy.ndarray

In [81]:
X=data[['R&D Spend','Administration','Marketing Spend','State']]

In [82]:
X.shape

(50, 4)

In [83]:
from sklearn.linear_model import LinearRegression

In [84]:
model=LinearRegression()

In [85]:
 #model.fit(X,y)  # bcoz state is cateogorical variable (has String) , encoding is required.

In [86]:
# convert into numbers : Label encoding
state = data['State']

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
state_le = LabelEncoder()

In [89]:
state = state_le.fit_transform(state)

In [90]:
state 

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [91]:
state.shape

(50,)

In [92]:
import numpy

In [93]:
state = state.reshape(-1,1)  # convert 1D -> 2D

In [94]:
state.shape

(50, 1)

In [95]:
from sklearn.preprocessing import OneHotEncoder

In [96]:
state_ohe = OneHotEncoder()

In [97]:
state_dummy = state_ohe.fit_transform(state)   # error as it acceps only 2D

In [98]:
type(state_dummy)    # sparse type.  to convert sparse to numpy => .toarray() is required

scipy.sparse.csr.csr_matrix

In [99]:
state_final = state_dummy.toarray()   # since 1st state was NY. there for third column is NY,  2nd row 1 column iso one =>california
# california, florida, newyork => this sparse matrix is producesd behind the scene.
# lets verify. 5ht sate is florida in data set => fifth row 2nd col shold be 1.  yes it is....great...

# Multicollinearityisue:
# if u knwo two of them automaticall i knwo the 3rd, 
# sol:
#     have to elimante one feature.

In [100]:
state_final=state_final[: , 0:2]

In [101]:
# replacing state field with this above one


In [102]:
type(X) 

pandas.core.frame.DataFrame

In [103]:
X = X.values   # X converting to array

In [104]:
state_final.shape

(50, 2)

In [105]:
X=X[:, 0:3]

In [106]:
X.shape

(50, 3)

In [107]:
X_final = numpy.hstack( (X, state_final))

In [108]:
X_final

array([[165349.2, 136897.8, 471784.1, 0.0, 0.0],
       [162597.7, 151377.59, 443898.53, 1.0, 0.0],
       [153441.51, 101145.55, 407934.54, 0.0, 1.0],
       [144372.41, 118671.85, 383199.62, 0.0, 0.0],
       [142107.34, 91391.77, 366168.42, 0.0, 1.0],
       [131876.9, 99814.71, 362861.36, 0.0, 0.0],
       [134615.46, 147198.87, 127716.82, 1.0, 0.0],
       [130298.13, 145530.06, 323876.68, 0.0, 1.0],
       [120542.52, 148718.95, 311613.29, 0.0, 0.0],
       [123334.88, 108679.17, 304981.62, 1.0, 0.0],
       [101913.08, 110594.11, 229160.95, 0.0, 1.0],
       [100671.96, 91790.61, 249744.55, 1.0, 0.0],
       [93863.75, 127320.38, 249839.44, 0.0, 1.0],
       [91992.39, 135495.07, 252664.93, 1.0, 0.0],
       [119943.24, 156547.42, 256512.92, 0.0, 1.0],
       [114523.61, 122616.84, 261776.23, 0.0, 0.0],
       [78013.11, 121597.55, 264346.06, 1.0, 0.0],
       [94657.16, 145077.58, 282574.31, 0.0, 0.0],
       [91749.16, 114175.79, 294919.57, 0.0, 1.0],
       [86419.7, 153514.1

In [109]:
model.fit(X_final,y)

LinearRegression()

In [110]:
model.coef_   # the one which is more positive has the most weightage on predicting y. here R and D spend has the most weightage.
 #behind the scenes it calculates the weights for each coloumn or feature.


array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  4.18870191e+01,
        2.40675812e+02])

In [111]:
model.predict[[0]]

TypeError: 'method' object is not subscriptable